version: '2.1'

volumes:
  unifi-config:
  unifi-log:
  unifi-log2:
  unifi-run:
  unifi-run2:
  unifi-work:
  pihole:
  dnsmasq:
  cups:

services:
  unifi:
    image: ryansch/unifi-rpi:6.1.51-arm32v7
    ports:
      - "3478:3478/udp"
      - "6789:6789"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "10001:10001/udp"
    volumes:
      - unifi-config:/var/lib/unifi
      - unifi-log:/usr/lib/unifi/logs
      - unifi-log2:/var/log/unifi
      - unifi-run:/usr/lib/unifi/run
      - unifi-run2:/run/unifi
      - unifi-work:/usr/lib/unifi/work
    restart: unless_stopped
  pihole:
    build: ./pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "9080:80/tcp"
      - "9443:443/tcp"
    privileged: true
    environment:
    #  WEBPASSWORD: # set in balena
      TZ: Europe/Bucharest
      DNSMASQ_LISTENING: wlan0
      INTERFACE: wlan0
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    network_mode: host
    restart: unless_stopped
  cups:
    build: ./cups
    ports:
      - "80"
    privileged: true
    network_mode: host
    volumes:
      - 'cups:/etc/cups'
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    restart: unless_stopped
