version: '2'

volumes:
  unifi-config:
  unifi-log:
  unifi-log2:
  unifi-run:
  unifi-run2:
  unifi-work:
  pihole:
  dnsmasq:

services:
  unifi:
    image: ryansch/unifi-rpi:6.1.26-arm32v7
    ports:
      - "3478:3478/udp"
      - "6789:6789"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "10001:10001/udp"
    volumes:
      - unifi-config:/var/lib/unifi
      - unifi-log:/usr/lib/unifi/logs
      - unifi-log2:/var/log/unifi
      - unifi-run:/usr/lib/unifi/run
      - unifi-run2:/run/unifi
      - unifi-work:/usr/lib/unifi/work
  pihole:
    build: ./pihole
    privileged: true
    environment:
    #  WEBPASSWORD: # set in balena
      TZ: Europe/Bucharest
      DNSMASQ_LISTENING: wlan0
      INTERFACE: wlan0
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    network_mode: host
